### PR TITLE
lab-lambda-functions Tiago Paim

### PR DESCRIPTION
**Pull request by cleanspin**

### CODE REVIEW

**Comment by cleanspin** [comment]
check

**Comment by ta-data-lis** [comment]
Hey Tiago, 

The notebook is pretty much empty (only challenge 2), so maybe you forgot to commit the final one...?

Close this pull request again when you do :+1:

**Comment by cleanspin** [comment]
:O I don't know what happened. Sorry, I think I might've ended doing the notebook, commited it and forgot to push before doing the pull request.

**Comment by ta-data-lis** [comment]
Lab checked, good job!

**Challenge 1**
Try to check this for the second question, it may be useful:
https://www.youtube.com/watch?v=oqMuzgsY_2k

Keep up the good work!

**Pull request closed without merging**
